# Generated by Django 3.0.4 on 2020-04-07 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientNumber', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientcity', models.CharField(max_length=100)),
                ('patientSex', models.CharField(max_length=100)),
                ('patientDOB', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 12, 50, 49, 318064))),
                ('careNumber', models.CharField(max_length=100)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('sickness', models.CharField(choices=[('Malaria', 'Malaria'), ('Covid 19', 'Covid 19'), ('Typhoid fever', 'Typhoid fever'), ('Kidney Stone', 'Kidney Stone'), ('Tooth Decay', 'Tooth Decay')], default='green', max_length=100)),
                ('RegistrationLocation', models.CharField(max_length=100)),
                ('doctorName', models.CharField(max_length=100)),
            ],
        ),
    ]
